### ISSUE TITLE
What happened to compute_vmaf()?

### ISSUE THREAD

**Issue by UnitedMarsupials** [Netflix/vmaf#1299]
After upgrading vmaf to 3.0.0 (release candidate 1), I can no longer compile x265 with VMAF-support:

```
c++ -DENABLE_HDR10_PLUS -DENABLE_LIBVMAF -DEXPORT_C_API=1 -DHAVE_INT_TYPES_H=1 -DHIGH_BIT_DEPTH=0 -DX265_ARCH_X86=1 -DX265_DEPTH=8 -DX265_NS=x265 -DX86_64=1 -D__STDC_LIMIT_MACROS=1 -I/opt/include/libvmaf -I/n/home/ports/multimedia/x265/work/source/. -I/n/home/ports/multimedia/x265/work/source/dynamicHDR10 -I/n/home/ports/multimedia/x265/work/.build -I/n/home/ports/multimedia/x265/work/source/common -I/n/home/ports/multimedia/x265/work/source/encoder -O2 -pipe -march=sandybridge -O3 -fstack-protector-strong -isystem /opt/include -fno-strict-aliasing  -isystem /opt/include -O2 -pipe -march=sandybridge -O3 -fstack-protector-strong -isystem /opt/include -fno-strict-aliasing  -isystem /opt/include  -DNDEBUG   -Wall -Wextra -Wshadow -std=gnu++11 -fPIC -Wno-array-bounds -ffast-math -mstackrealign -fno-exceptions -Wno-uninitialized -MD -MT encoder/CMakeFiles/encoder.dir/api.cpp.o -MF encoder/CMakeFiles/encoder.dir/api.cpp.o.d -o encoder/CMakeFiles/encoder.dir/api.cpp.o -c /n/home/ports/multimedia/x265/work/source/encoder/api.cpp
/n/home/ports/multimedia/x265/work/source/encoder/api.cpp:1925:5: error: use of undeclared identifier 'compute_vmaf'
    compute_vmaf(&score, vcd->format, data->width, data->height, read_frame, data, vcd->model_path, vcd->log_path, vcd->log_fmt, vcd->disable_clip, vcd->disable_avx, vcd->enable_transform, vcd->phone_model, vcd->psnr, vcd->ssim, vcd->ms_ssim, vcd->pool, vcd->thread, vcd->subsample, vcd->enable_conf_interval);
    ^
/n/home/ports/multimedia/x265/work/source/encoder/api.cpp:2027:5: error: use of undeclared identifier 'compute_vmaf'
    compute_vmaf(&score, vcd->format, vmafframedata->width, vmafframedata->height, read_frame, vmafframedata, vcd->model_path, vcd->log_path, vcd->log_fmt, vcd->disable_clip, vcd->disable_avx, vcd->enable_transform, vcd->phone_model, vcd->psnr, vcd->ssim, vcd->ms_ssim, vcd->pool, vcd->thread, vcd->subsample, vcd->enable_conf_interval);
    ^
2 errors generated.
```
Any advice?

**Comment by kylophone** [comment]
`compute_vmaf()` has been marked deprecated since v2.0 (~3 years). With the recent libvmaf v3.0 release the API has been removed completely.
