### ISSUE TITLE
Error in compute_vmaf while trying to build vmaf into ffmpeg

### ISSUE THREAD

**Issue by SobhanAbedi** [Netflix/vmaf#880]
Hi. I'm trying to compile ffmpeg (on Ubuntu) with vmaf using [ffmpeg compilation guide](https://trac.ffmpeg.org/wiki/CompilationGuide/Ubuntu). I get the following error: (I've replace my file system with $HOME/ in the report)
```
libavfilter/vf_libvmaf.c: In function ‘compute_vmaf_score’:
libavfilter/vf_libvmaf.c:172:5: warning: ‘compute_vmaf’ is deprecated [-Wdeprecated-declarations]
  172 |     s->error = compute_vmaf(&s->vmaf_score, format, s->width, s->height,
      |     ^
In file included from $HOME/ffmpeg_build/include/libvmaf/libvmaf.h:25,
                 from libavfilter/vf_libvmaf.c:28:
$HOME/ffmpeg_build/include/libvmaf/compute_vmaf.h:66:5: note: declared here
   66 | int compute_vmaf(double* vmaf_score, char* fmt, int width, int height, int (*read_frame)(float *ref_data, float *main_data, float *temp_data, int stride_byte, void *user_data),
      |     ^~~~~~~~~~~~
```
this is the code i used to compile vmaf:
```
cd ~/ffmpeg_sources && \
wget https://github.com/Netflix/vmaf/archive/v2.1.1.tar.gz && \
tar xvf v2.1.1.tar.gz && \
mkdir -p vmaf-2.1.1/libvmaf/build &&\
cd vmaf-2.1.1/libvmaf/build && \
meson setup -Denable_tests=false -Denable_docs=false --buildtype=release --default-library=static .. --prefix "$HOME/ffmpeg_build" --bindir="$HOME/ffmpeg_build/bin" --libdir="$HOME/ffmpeg_build/lib" && \
ninja && \
ninja install
```
this is the code i used to compile ffmpeg:
```
cd ~/ffmpeg_sources && \
wget -O ffmpeg-snapshot.tar.bz2 https://ffmpeg.org/releases/ffmpeg-snapshot.tar.bz2 && \
tar xjvf ffmpeg-snapshot.tar.bz2 && \
cd ffmpeg && \
PATH="$HOME/bin:$PATH" PKG_CONFIG_PATH="$HOME/ffmpeg_build/lib/pkgconfig" ./configure \
  --prefix="$HOME/ffmpeg_build" \
  --pkg-config-flags="--static" \
  --extra-cflags="-I$HOME/ffmpeg_build/include" \
  --extra-ldflags="-L$HOME/ffmpeg_build/lib" \
  --extra-libs="-lpthread -lm" \
  --ld="g++" \
  --bindir="$HOME/ffmpeg_build/bin" \
  --enable-gpl \
  --enable-gnutls \
  --enable-libass \
  --enable-libfdk-aac \
  --enable-libfreetype \
  --enable-libmp3lame \
  --enable-libopus \
  --enable-libdav1d \
  --enable-libvorbis \
  --enable-libvpx \
  --enable-libx264 \
  --enable-libx265 \
  --enable-libvmaf \
  --enable-nonfree && \
PATH="$HOME/bin:$PATH" make && \
make install && \
hash -r
```

**Comment by kylophone** [comment]
Yes, that function is deprecated, hence the warning. Are you compiling ffmpeg with `-Wall` or similar?

FYI, there is a new FFmpeg libvmaf filter version coming soon. See: http://ffmpeg.org/pipermail/ffmpeg-devel/2021-June/281593.html for more info.

**Comment by SobhanAbedi** [comment]
I was aware of the deprecation. I was wondering if the old version still works or not.
I'm receiving an error under the warning which stops the vmaf from being built with ffmpeg. (ffmpeg gets built but vamf is not included)
I'm not compiling manually. I'm compiling using the make file included in the ffmpeg repo (following the guide).
I checked the make file and didn't find -wall flag. Sorry I'm a novice builder.
[Makefile.txt](https://github.com/Netflix/vmaf/files/6735570/Makefile.txt)

**Comment by kylophone** [comment]
It will still build with vmaf v2.1.1. Can you paste the actual compilation error here? What you pasted [here](https://github.com/Netflix/vmaf/issues/880#issue-932932371) is only a warning.

**Comment by SobhanAbedi** [comment]
I don't get an error besides `s->error = compute_vmaf(&s->vmaf_score, format, s->width, s->height,`. but vmaf is not included in the compiled ffmpeg. and this is the last place in compilation log that libvmaf is mentioned. I don't get a libvmaf compilation confirmation. (but my other libraries do change after compilation. so the overall compilation is successful)
thank you for you help

**Comment by 1480c1** [comment]
libvmaf should be in the final ffmpeg, try checking `./ffmpeg -h filter=libvmaf`

**Comment by SobhanAbedi** [comment]
I'm really sorry. A restart fixed the problem. (I didn't rebuild ffmpeg. after a restart libvmaf showed up)
Thanks for your help.
